language: node_js
node_js:
  - "12"
cache:
  directories:
    - node_modules
branchs:
  only:
    - main
addons:
  ssh_known_hosts: $SERVER_IP
before_install: 
  - chmod 600 id_rsa_blog
  - echo -e "Host $SERVER_IP\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - yarn global add vuepress@next
install:
  - yarn install
script:
  - yarn build
after_success:
  - cd docs/.vuepress/dist
  - scp -o stricthostkeychecking=no -r ./* $SERVER_NAME@$SERVER_IP:/root/web/blog
