language: node_js
node_js:
- '12'
cache:
  directories:
  - node_modules
branchs:
  only:
  - main
addons:
  ssh_known_hosts: 162.14.64.8
before_install:
- openssl aes-256-cbc -K $encrypted_d0435390278d_key -iv $encrypted_d0435390278d_iv
  -in id_rsa_blog.enc -out ~/.ssh/id_rsa_blog -d
- chmod 700 ~/.ssh
- chmod 600 ~/.ssh/id_rsa_blog
- yarn global add vuepress@next
install:
- yarn install
script:
- yarn build
- pwd
- cd docs/.vuepress/dist
- pwd
- scp -o stricthostkeychecking=no -r ./* $SERVER_NAME@$SERVER_IP:/$SERVER_NAME/web/blog