language: node_js
node_js:
- '12'
cache:
  directories:
  - node_modules
branchs:
  only:
  - main
before_install:
- openssl aes-256-cbc -K $encrypted_d0435390278d_key -iv $encrypted_d0435390278d_iv
  -in id_rsa_blog.enc -out ~/.ssh/id_rsa_blog -d
- chmod 700 ~/.ssh
- chmod 600 ~/.ssh/id_rsa_blog
after_success:
- echo aabbcc